/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoVentana;

import proyecto.Coalicion;
import proyecto.FormacionPolitica;
import proyecto.ListaPart;
import proyecto.PartidoPolitico;
import java.io.BufferedInputStream;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZHONG HAO LIN CHEN, ADRIAN DAVID MORILLAS MARCO, CLARA EUGENIA PALOMARES CALVO
 */
public class jfCoalicion extends javax.swing.JFrame {

    Vector datos = new Vector();
    Vector datos2 = new Vector();
    ListaPart listPartPoli;  //Lista de partidos
    ListaPart listPartPoliCoali; //Partidos seleccionados para una coalicion
    Coalicion coali;
    ArrayList<Coalicion> listCoali;
    FormacionPolitica forma;   
    ArrayList<FormacionPolitica> listForma;
    DefaultTableModel tmodelPartPoli = new DefaultTableModel();
    DefaultTableModel tmodelPartPoli2 = new DefaultTableModel();
    DefaultTableModel tmodelCoalicion = new DefaultTableModel();
    
    /**
     * Creates new form jfCoalcion
    */
    public jfCoalicion() {
        initComponents();
        
        listPartPoli = new ListaPart();
        listPartPoliCoali = new ListaPart();
        coali = new Coalicion();
        listCoali = new ArrayList<Coalicion>();
        
        FormacionPolitica forma = new Coalicion(); 
        listForma = new ArrayList<FormacionPolitica>();
        
        //Centrar la ventana
        this.setLocationRelativeTo(null);       
        
        tmodelPartPoli.addColumn("Nombre");
        tmodelPartPoli.addColumn("Siglas");
        tmodelPartPoli.addColumn("Logo");
        
        tmodelPartPoli2.addColumn("Nombre");
        tmodelPartPoli2.addColumn("Siglas");
        tmodelPartPoli2.addColumn("Logo");
        
        tmodelCoalicion.addColumn("Nombre");
        tmodelCoalicion.addColumn("Siglas");
        tmodelCoalicion.addColumn("Logo");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelSiglas = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldSiglas = new javax.swing.JTextField();
        jTextFieldLogo = new javax.swing.JTextField();
        jScrollPaneMili = new javax.swing.JScrollPane();
        jTablePartPoli = new javax.swing.JTable();
        jButtonCargarLista = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelSubtitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaColicion = new javax.swing.JTable();
        jButtonGuardarListaCoali = new javax.swing.JButton();
        jButtonCargarListaCoali = new javax.swing.JButton();
        jButtonAgregarCoalicion = new javax.swing.JButton();
        jButtonAddPartido = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePartAna = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomFicheroPart = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNomFicheroCoa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(150, 100, 230));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitulo.setText("Coaliciones");

        jLabelNombre.setText("Nombre");

        jLabelSiglas.setText("Siglas");

        jLabelLogo.setText("Logo");

        jTextFieldSiglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSiglasActionPerformed(evt);
            }
        });

        jTablePartPoli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Siglas", "Logo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneMili.setViewportView(jTablePartPoli);

        jButtonCargarLista.setText("Cargar lista de partidos");
        jButtonCargarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarListaActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabelSubtitulo.setText("Lista de Coaliciones y formaciones");

        jTableListaColicion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Siglas", "Logo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableListaColicion);

        jButtonGuardarListaCoali.setText("Guardar lista de coaliciones y formaciones");
        jButtonGuardarListaCoali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarListaCoaliActionPerformed(evt);
            }
        });

        jButtonCargarListaCoali.setText("Cargar lista de coaliciones y formaciones");
        jButtonCargarListaCoali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarListaCoaliActionPerformed(evt);
            }
        });

        jButtonAgregarCoalicion.setText("Agregar coalicion o formacion");
        jButtonAgregarCoalicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarCoalicionActionPerformed(evt);
            }
        });

        jButtonAddPartido.setText("Añadir partido seleccionado a la coalición nueva");
        jButtonAddPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPartidoActionPerformed(evt);
            }
        });

        jTablePartAna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Siglas", "Logo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTablePartAna);

        jLabel1.setText("Partidos añadidos a la coalición ");

        jLabel2.setText("Nombre del fichero de partidos");

        jLabel3.setText("Nombre de coaliciones a guardar o cargar");

        jTextFieldNomFicheroCoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomFicheroCoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelSiglas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldSiglas, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jTextFieldLogo))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAddPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonSalir)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPaneMili, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSubtitulo)
                            .addComponent(jButtonAgregarCoalicion)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonCargarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNomFicheroPart))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonGuardarListaCoali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCargarListaCoali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomFicheroCoa, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(209, 209, 209))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCargarLista)
                    .addComponent(jTextFieldNomFicheroPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneMili, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButtonAddPartido)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSiglas)
                            .addComponent(jTextFieldSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLogo)
                            .addComponent(jTextFieldLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addComponent(jButtonAgregarCoalicion)
                .addGap(18, 18, 18)
                .addComponent(jLabelSubtitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonGuardarListaCoali)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCargarListaCoali)
                            .addComponent(jTextFieldNomFicheroCoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCargarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarListaActionPerformed
        this.LeerArchivoLista(); //Invocamos el metodo de Leer para que el boton cargue nuestra lista de partidos
    }//GEN-LAST:event_jButtonCargarListaActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAddPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPartidoActionPerformed
        String nombreSeleccionado = "";  //String incializado a vacio 
        nombreSeleccionado = this.jTablePartPoli.getValueAt(jTablePartPoli.getSelectedRow(),0).toString();
        String siglasSeleccionado = "";  //String incializado a vacio 
        siglasSeleccionado = this.jTablePartPoli.getValueAt(jTablePartPoli.getSelectedRow(),1).toString();
        String logoSeleccionado = "";  //String incializado a vacio 
        logoSeleccionado = this.jTablePartPoli.getValueAt(jTablePartPoli.getSelectedRow(),2).toString();
        
        PartidoPolitico partPoli2 = new PartidoPolitico(); //Creamos un nuevo partido politico de la Clase PartidoPolitico
             
             //Le asignamos el nombre, siglas y logo del texto que hemos rellenado en la interfaz
             partPoli2.setNombre(nombreSeleccionado); 
             partPoli2.setSiglas(siglasSeleccionado);
             partPoli2.setLogo(logoSeleccionado);
             
                        
             listPartPoliCoali.add(partPoli2);

             //A la hora de rellenar la tabla tambien le añadiremos lo que hemos escrito en la barra de texto
             datos = new Vector();
             datos.addElement(nombreSeleccionado);
             datos.addElement(siglasSeleccionado);
             datos.addElement(logoSeleccionado);
             
             tmodelPartPoli2.addRow(datos);

             jTablePartAna.setModel(tmodelPartPoli2);

    }//GEN-LAST:event_jButtonAddPartidoActionPerformed

    private void jButtonAgregarCoalicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarCoalicionActionPerformed
             ArrayList<ListaPart> listPart = new ArrayList<ListaPart>(); //Creamos un nuevo partido politico de la Clase PartidoPolitico
             
             listPart.add(listPartPoliCoali);
                         
             forma = new Coalicion();
             
             //Le asignamos el nombre, siglas y logo del texto que hemos rellenado en la interfaz a la coalicion
             forma.setNombre(jTextFieldNombre.getText()); 
             forma.setSiglas(jTextFieldSiglas.getText());
             forma.setLogo(jTextFieldLogo.getText());
             
             //A la coalicion le añadimos la lista de partidos politicos de la segunda tabla
             forma.addPartido(listPartPoliCoali);         
             listForma.add(forma);//Y a la lista de coaliciones le añadimos una coalicion

             //A la hora de rellenar la tabla tambien le añadiremos lo que hemos escrito en la barra de texto
             datos2 = new Vector();
             datos2.addElement(jTextFieldNombre.getText());
             datos2.addElement(jTextFieldSiglas.getText());
             datos2.addElement(jTextFieldLogo.getText());
             
             tmodelCoalicion.addRow(datos2);

             jTableListaColicion.setModel(tmodelCoalicion);
             
             //Limpiar la tabla 2 al agregar una coalicion
             this.tmodelPartPoli2.getDataVector().removeAllElements();
             tmodelPartPoli2.fireTableDataChanged();
    }//GEN-LAST:event_jButtonAgregarCoalicionActionPerformed

    private void jTextFieldSiglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSiglasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSiglasActionPerformed

    private void jButtonGuardarListaCoaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarListaCoaliActionPerformed
        this.Guardar();
    }//GEN-LAST:event_jButtonGuardarListaCoaliActionPerformed

    private void jButtonCargarListaCoaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarListaCoaliActionPerformed
        this.CargarListaCoali();
    }//GEN-LAST:event_jButtonCargarListaCoaliActionPerformed

    private void jTextFieldNomFicheroCoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomFicheroCoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomFicheroCoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfCoalicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfCoalicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfCoalicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfCoalicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfCoalicion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPartido;
    private javax.swing.JButton jButtonAgregarCoalicion;
    private javax.swing.JButton jButtonCargarLista;
    private javax.swing.JButton jButtonCargarListaCoali;
    private javax.swing.JButton jButtonGuardarListaCoali;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSiglas;
    private javax.swing.JLabel jLabelSubtitulo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneMili;
    private javax.swing.JTable jTableListaColicion;
    private javax.swing.JTable jTablePartAna;
    private javax.swing.JTable jTablePartPoli;
    private javax.swing.JTextField jTextFieldLogo;
    private javax.swing.JTextField jTextFieldNomFicheroCoa;
    private javax.swing.JTextField jTextFieldNomFicheroPart;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldSiglas;
    // End of variables declaration//GEN-END:variables

    private void LeerArchivoLista() {
        try 
        {
            String nomArch = jTextFieldNomFicheroPart.getText();
            FileInputStream fis = new FileInputStream(nomArch); 
            BufferedInputStream bis = new BufferedInputStream(fis); 
            DataInputStream dis = null; 
                       
            //Inicializamos las cadenas en vacio
            dis = new DataInputStream(bis); 
            String linea = "";
            String strNombre = "";
            String strSiglas = "";
            String strLogo = "";
            PartidoPolitico partPoli;
            
            //Bucle para recorrer por linea del txt de la lista de partidos politicos
            while ((linea = dis.readLine()) != null ) 
            {                 
                strNombre = linea.substring(0, linea.indexOf(";"));
                linea = linea.substring(linea.indexOf(";")+ 1, linea.length());
                
                strSiglas = linea.substring(0, linea.indexOf(";"));
                
                linea = linea.substring(linea.indexOf(";")+ 1, linea.length());
                strLogo = linea.substring(0, linea.indexOf(";"));
                
                //Llenando la lista de los partidos politicos
                partPoli = new PartidoPolitico();
             
                partPoli.setNombre(strNombre);
                partPoli.setSiglas(strSiglas);
                partPoli.setLogo(strLogo);
             
                listPartPoli.add(partPoli);
                
                //Llenado de la tabla
                datos = new Vector();
                datos.addElement(strNombre);
                datos.addElement(strSiglas);
                datos.addElement(strLogo);

                tmodelPartPoli.addRow(datos);
                jTablePartPoli.setModel(tmodelPartPoli);
                
                //Escribirlo en consola
                System.out.println(strNombre);
                System.out.println(strSiglas);
                System.out.println(strLogo);
           }            
            //Contador de partidos
            System.out.println("Cantidad Partidos Politicos " + listPartPoli.size());
               
        }
        catch(IOException e)
        {
            System.out.println("Error en la lectura del archivo");//Mensaje de error de lectura
        }
    }

    private void Guardar() {
            try {
            String nomArch = jTextFieldNomFicheroCoa.getText();           
            //Aqui asignamos donde queremos guardar el fichero txt
            BufferedWriter out = new BufferedWriter(new FileWriter(nomArch));
            //Este bucle for recorre toda la lista de partidos politicos y va escribiendo en orden nombre, siglas y logo
            for(FormacionPolitica fp:this.listForma){
                
                //Nombre
                out.write(fp.getNombre() + ";");
                 
                //Siglas
                out.write(fp.getSiglas() + ";");
                
                //Logo
                out.write(fp.getLogo() + ";");
                
                //Salto de linea
                out.write(System.getProperty("line.separator"));
            }          
            out.close();
        } catch (IOException e) {}
    }

    private void CargarListaCoali() {
        try 
        {
            //Directorio de donde queremos leer el archivo
            String nomArch = jTextFieldNomFicheroCoa.getText();
            FileInputStream fis = new FileInputStream(nomArch); 
            BufferedInputStream bis = new BufferedInputStream(fis); 
            DataInputStream dis = null; 
            
            //Inicializamos las cadenas en vacio
            dis = new DataInputStream(bis); 
            String linea = "";
            String strNombreC = "";
            String strSiglasC = "";
            String strLogoC = "";
            FormacionPolitica fcoali;
            ArrayList<FormacionPolitica> listFormaCoali = new ArrayList();
            
            //Bucle para recorrer por linea del txt de la lista de partidos politicos
            while ((linea = dis.readLine()) != null ) 
            {                 
                strNombreC = linea.substring(0, linea.indexOf(";"));
                linea = linea.substring(linea.indexOf(";")+ 1, linea.length());
                
                strSiglasC = linea.substring(0, linea.indexOf(";"));
                
                linea = linea.substring(linea.indexOf(";")+ 1, linea.length());
                strLogoC = linea.substring(0, linea.indexOf(";"));
                            
                //Llenando los parametros de la coalicion y la lista de coaliciones
                fcoali = new Coalicion();
             
                fcoali.setNombre(strNombreC);
                fcoali.setSiglas(strSiglasC);
                fcoali.setLogo(strLogoC);
                //A la lista de coalicion le agrego la coalicion creada
                this.listForma.add(fcoali);                
                
                //Llenado de la tabla
                datos2 = new Vector();
                datos2.addElement(strNombreC);
                datos2.addElement(strSiglasC);
                datos2.addElement(strLogoC);

                tmodelCoalicion.addRow(datos2);
                jTableListaColicion.setModel(tmodelCoalicion);
                
                //Escribirlo en consola
                System.out.print(" Nombre formacion:"+strNombreC);
                System.out.print(" Siglas formacion:"+strSiglasC);
                System.out.println(" Logo formacion:"+strLogoC);
           }            
            //Contador de partidos
            System.out.println("Cantidad Coaliciones y formaciones " + listFormaCoali.size());
               
        }
        catch(IOException e)
        {
            System.out.println("Error en la lectura del archivo");//Mensaje de error de lectura
        }
    }
}
