/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoVentana;

import proyecto.Lista;
import proyecto.Votante;
import proyecto.Militante;
import proyecto.Simpatizante;
import proyecto.PartidoPolitico;
import java.io.BufferedInputStream;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZHONG HAO LIN CHEN, ADRIAN DAVID MORILLAS MARCO, CLARA EUGENIA PALOMARES CALVO
 */
public class jfMiembros extends javax.swing.JFrame {
    
    Vector datos = new Vector();
    //Lista listMili;
    Lista listSimp;
    Lista listMiem;
    ArrayList<Militante> listMili;
    DefaultTableModel tmodelMiem = new DefaultTableModel();
    private String strNomPartPoli;
    
    private Scanner sc = new Scanner (System.in);
    private FileOutputStream archivo;
    private FileInputStream archivoInput;
    private ObjectOutputStream salida;
    private ObjectInputStream entrada;
    
    /**
     * Creates new form jfMilitante
     */
    public jfMiembros() {
        initComponents();
        
        //Centrar la ventana
        this.setLocationRelativeTo(null);
        
        listMili = new ArrayList<Militante>(); 
        //listMili =  new Lista();
        listSimp = new Lista();
        listMiem = new Lista();
        
        tmodelMiem.addColumn("Tipo votante");
        tmodelMiem.addColumn("Nombre");
        tmodelMiem.addColumn("Apellidos");
        tmodelMiem.addColumn("Edad");
        tmodelMiem.addColumn("Profesion");
        tmodelMiem.addColumn("Genero");
        tmodelMiem.addColumn("Siglas Partido");
        tmodelMiem.addColumn("Encuesta 1");
        tmodelMiem.addColumn("Encuesta 2");
        
        tmodelMiem.addColumn("Cuota");
        tmodelMiem.addColumn("Carne");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jButtonAgregarM = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jLabelProfesion = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jLabelSiglas = new javax.swing.JLabel();
        jLabelEncuesta = new javax.swing.JLabel();
        jLabelEncuesta2 = new javax.swing.JLabel();
        texFieldNombre = new javax.swing.JTextField();
        texFieldApellidos = new javax.swing.JTextField();
        texFieldEdad = new javax.swing.JTextField();
        texFieldProfesion = new javax.swing.JTextField();
        texFieldGenero = new javax.swing.JTextField();
        texFieldSiglas = new javax.swing.JTextField();
        texFieldEncuesta = new javax.swing.JTextField();
        texFieldEncuesta2 = new javax.swing.JTextField();
        jScrollPaneMili = new javax.swing.JScrollPane();
        jTableMiem = new javax.swing.JTable();
        jLabelCuota = new javax.swing.JLabel();
        jLabelCarne = new javax.swing.JLabel();
        texFieldCuota = new javax.swing.JTextField();
        texFieldCarne = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCargar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        texFieldSoM = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomFichero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jButtonSalir.setBackground(new java.awt.Color(200, 240, 240));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonAgregarM.setText("Agregar militante");
        jButtonAgregarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarMActionPerformed(evt);
            }
        });

        jLabelNombre.setText("Nombre");

        jLabelApellidos.setText("Apellidos");

        jLabelEdad.setText("Edad");

        jLabelProfesion.setText("Profesión");

        jLabelGenero.setText("Género");

        jLabelSiglas.setText("Siglas Partido");

        jLabelEncuesta.setText("Pregunta 1:?");

        jLabelEncuesta2.setText("Pregunta 2:?");

        texFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texFieldNombreActionPerformed(evt);
            }
        });

        texFieldApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texFieldApellidosActionPerformed(evt);
            }
        });

        texFieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texFieldEdadActionPerformed(evt);
            }
        });

        texFieldProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texFieldProfesionActionPerformed(evt);
            }
        });

        texFieldGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texFieldGeneroActionPerformed(evt);
            }
        });

        texFieldSiglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texFieldSiglasActionPerformed(evt);
            }
        });

        texFieldEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texFieldEncuestaActionPerformed(evt);
            }
        });

        jTableMiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tipo votante", "Nombre", "Apellidos", "Edad", "Profesión", "Género", "Siglas Partido", "Encuesta", "Encuesta 2", "Cuota", "Carne"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneMili.setViewportView(jTableMiem);

        jLabelCuota.setText("Cuota");

        jLabelCarne.setText("Carne");

        texFieldCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texFieldCuotaActionPerformed(evt);
            }
        });

        texFieldCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texFieldCarneActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar Lista de Militantes");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCargar.setText("Cargar Lista de Militantes");
        jButtonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo votante");

        texFieldSoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texFieldSoMActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar Simpatizante");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre de fichero a guardar o cargar");

        jTextFieldNomFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomFicheroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPaneMili)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNomFichero))
                                .addGap(621, 621, 621)
                                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelProfesion)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonAgregarM)
                                .addGap(45, 45, 45)
                                .addComponent(jButton1))
                            .addComponent(jLabelSiglas))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(texFieldSoM, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(texFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelApellidos)
                                    .addComponent(jLabelEdad)
                                    .addComponent(jLabelGenero))
                                .addGap(79, 79, 79)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(texFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(texFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(texFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(texFieldProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(texFieldSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCuota)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEncuesta2)
                                    .addComponent(jLabelEncuesta)
                                    .addComponent(jLabelCarne))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(texFieldEncuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(texFieldEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(texFieldCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(texFieldCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEncuesta)
                    .addComponent(texFieldEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(texFieldSoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texFieldEncuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEncuesta2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCuota)
                            .addComponent(texFieldCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCarne)
                            .addComponent(texFieldCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelApellidos))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEdad)
                            .addComponent(texFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProfesion)
                            .addComponent(texFieldProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGenero)
                    .addComponent(texFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSiglas)
                    .addComponent(texFieldSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarM)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneMili, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonGuardar)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCargar)
                            .addComponent(jTextFieldNomFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.setVisible(false);              
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAgregarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarMActionPerformed
        Militante mili = new Militante();
        
        String arrayEncuesta[] = new String[2];

        mili.setTipo(texFieldSoM.getText());
        mili.setNombre(texFieldNombre.getText());
        mili.setApellidos(texFieldApellidos.getText());

        //Cambio de dato de entero a String
        mili.setEdad(Integer.parseInt(texFieldEdad.getText()));

        mili.setProfesion(texFieldProfesion.getText());
        mili.setGenero(texFieldGenero.getText().charAt(0));
        mili.setSiglas(texFieldSiglas.getText());
        arrayEncuesta[0] = texFieldEncuesta.getText();
        arrayEncuesta[1] = texFieldEncuesta2.getText();
        mili.setEncuestas(arrayEncuesta);

        mili.setCuota(Double.parseDouble(texFieldCuota.getText()));
        mili.setCarnet(texFieldCarne.getText());
        
        listMili.add(mili);
        listMiem.add(mili);
       
        //rellenado de la tabla
        datos = new Vector();
        datos.addElement(texFieldSoM.getText());
        datos.addElement(texFieldNombre.getText());
        datos.addElement(texFieldApellidos.getText());
        datos.addElement(Integer.parseInt(texFieldEdad.getText()));
        datos.addElement(texFieldProfesion.getText());
        datos.addElement(texFieldGenero.getText().charAt(0));
        datos.addElement(texFieldSiglas.getText());
        datos.addElement(texFieldEncuesta.getText());
        datos.addElement(texFieldEncuesta2.getText());
        datos.addElement(Double.parseDouble(texFieldCuota.getText()));
        datos.addElement(texFieldCarne.getText());

        tmodelMiem.addRow(datos);

        jTableMiem.setModel(tmodelMiem);
        
        //Imprimir por consola partido añadido
        System.out.print(" Tipo de votante:"+texFieldSoM.getText());
        System.out.print(" Nombre:"+texFieldNombre.getText());
        System.out.print(" Apellidos:"+texFieldApellidos.getText());
        System.out.print(" Edad:"+Integer.parseInt(texFieldEdad.getText())); 
        System.out.print(" Profesión:"+texFieldProfesion.getText());
        System.out.print(" Género:"+texFieldGenero.getText().charAt(0));
        System.out.print(" Siglas:"+texFieldSiglas.getText());
        System.out.print(" Pregunta 1:"+texFieldEncuesta.getText());
        System.out.print(" Pregunta 2:"+texFieldEncuesta2.getText());
        System.out.print(" Cuota:"+Double.parseDouble(texFieldCuota.getText()));
        System.out.println(" Carnet:"+texFieldCarne.getText());
    }//GEN-LAST:event_jButtonAgregarMActionPerformed

    private void texFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texFieldNombreActionPerformed

    private void texFieldApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texFieldApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texFieldApellidosActionPerformed

    private void texFieldCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texFieldCuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texFieldCuotaActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        try {
            this.GuardarMili();
        } catch (IOException ex) {
            Logger.getLogger(jfMiembros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarActionPerformed
        try {
            this.LeerArchivoMili();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jfMiembros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCargarActionPerformed

    private void texFieldEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texFieldEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texFieldEdadActionPerformed

    private void texFieldProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texFieldProfesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texFieldProfesionActionPerformed

    private void texFieldGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texFieldGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texFieldGeneroActionPerformed

    private void texFieldSiglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texFieldSiglasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texFieldSiglasActionPerformed

    private void texFieldCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texFieldCarneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texFieldCarneActionPerformed

    private void texFieldEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texFieldEncuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texFieldEncuestaActionPerformed

    private void texFieldSoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texFieldSoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texFieldSoMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Votante simp = new Simpatizante();
        
        String arrayEncuesta[] = new String[2];

        simp.setTipo(texFieldSoM.getText());
        simp.setNombre(texFieldNombre.getText());
        simp.setApellidos(texFieldApellidos.getText());

        //Cambio de dato de entero a String
        simp.setEdad(Integer.parseInt(texFieldEdad.getText()));

        simp.setProfesion(texFieldProfesion.getText());
        simp.setGenero(texFieldGenero.getText().charAt(0));
        simp.setSiglas(texFieldSiglas.getText());
        arrayEncuesta[0] = texFieldEncuesta.getText();
        arrayEncuesta[1] = texFieldEncuesta2.getText();
        simp.setEncuestas(arrayEncuesta);
    
        listSimp.add(simp); 
        listMiem.add(simp);
        
        //rellenado de la tabla
        datos = new Vector();
        datos.addElement(texFieldSoM.getText());
        datos.addElement(texFieldNombre.getText());
        datos.addElement(texFieldApellidos.getText());
        datos.addElement(Integer.parseInt(texFieldEdad.getText()));
        datos.addElement(texFieldProfesion.getText());
        datos.addElement(texFieldGenero.getText().charAt(0));
        datos.addElement(texFieldSiglas.getText());
        datos.addElement(texFieldEncuesta.getText());
        datos.addElement(texFieldEncuesta2.getText());
        datos.addElement(0.0);
        datos.addElement("nada");

        tmodelMiem.addRow(datos);

        jTableMiem.setModel(tmodelMiem);
        
        //Imprimir por consola partido añadido
        System.out.print(" Tipo de votante:"+texFieldSoM.getText());
        System.out.print(" Nombre:"+texFieldNombre.getText());
        System.out.print(" Apellidos:"+texFieldApellidos.getText());
        System.out.print(" Edad:"+Integer.parseInt(texFieldEdad.getText())); 
        System.out.print(" Profesión:"+texFieldProfesion.getText());
        System.out.print(" Género:"+texFieldGenero.getText().charAt(0));
        System.out.print(" Siglas:"+texFieldSiglas.getText());
        System.out.print(" Pregunta 1:"+texFieldEncuesta.getText());
        System.out.print(" Pregunta 2:"+texFieldEncuesta2.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldNomFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomFicheroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomFicheroActionPerformed

    public void setPartido(String NombrePartPoli){
        //Asignacion del partido al militante en la ventana de partidos
        this.strNomPartPoli = NombrePartPoli;
        this.texFieldSiglas.setText(this.strNomPartPoli);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMiembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMiembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMiembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMiembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMiembros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgregarM;
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelCarne;
    private javax.swing.JLabel jLabelCuota;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelEncuesta;
    private javax.swing.JLabel jLabelEncuesta2;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelProfesion;
    private javax.swing.JLabel jLabelSiglas;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneMili;
    private javax.swing.JTable jTableMiem;
    private javax.swing.JTextField jTextFieldNomFichero;
    private javax.swing.JTextField texFieldApellidos;
    private javax.swing.JTextField texFieldCarne;
    private javax.swing.JTextField texFieldCuota;
    private javax.swing.JTextField texFieldEdad;
    private javax.swing.JTextField texFieldEncuesta;
    private javax.swing.JTextField texFieldEncuesta2;
    private javax.swing.JTextField texFieldGenero;
    private javax.swing.JTextField texFieldNombre;
    private javax.swing.JTextField texFieldProfesion;
    private javax.swing.JTextField texFieldSiglas;
    private javax.swing.JTextField texFieldSoM;
    // End of variables declaration//GEN-END:variables

    public void GuardarMili() throws IOException{     
        try {
            String nomArch = jTextFieldNomFichero.getText();  
            //Aqui asignamos donde queremos guardar el fichero txt
             BufferedWriter out = new BufferedWriter(new FileWriter(nomArch));
                                     
            for(Militante mili:this.listMili){               
                //Tipo
                out.write(mili.getTipo() + ";");
                
                //Nombre
                out.write(mili.getNombre() + ";");
                 
                //Apellidos
                out.write(mili.getApellidos() + ";");
                
                //Edad
                out.write(mili.getEdad() + ";");
                
                //Profesion
                out.write(mili.getProfesion() + ";");
                
                //Genero
                out.write(mili.getGenero() + ";");
                
                //Siglas
                out.write(mili.getSiglas() + ";");
                
                //Encuesta
                out.write(mili.getEncuestas()[0] + ";");
                
                //Encuesta2
                out.write(mili.getEncuestas()[1] + ";");
                
                //Cuota
                out.write(mili.getCuota() + ";");
                
                //Carne
                out.write(mili.getCarnet() + ";");
                
                //Salto de linea
                out.write(System.getProperty("line.separator"));
            }           
            out.close();
        } catch(FileNotFoundException e){
         e.printStackTrace();
        }
        catch (IOException e) {}
}
   
    private void LeerArchivoMili() throws ClassNotFoundException{
        try 
        {
            String nomArch = jTextFieldNomFichero.getText();
            FileInputStream fis = new FileInputStream(nomArch); 
            BufferedInputStream bis = new BufferedInputStream(fis); 
            DataInputStream dis = null; 
            
            dis = new DataInputStream(bis); 
            String linea = "";
            String strSoM = "";
            String strNombre = "";
            String strApellidos = "";
            String strEdad = "";
            String strProfesion = "";
            String strGenero = "";
            String strSiglas = "";
            String strEncuesta[] = new String[2];                     
            String strCuota = "";
            String strCarne = "";
            
            Militante mili;
            
            //Bucle para recorrer por linea del txt de la lista de Miembros militantes
            while ((linea = dis.readLine()) != null ) 
            {       
                strSoM = linea.substring(0, linea.indexOf(";"));
                linea = linea.substring(linea.indexOf(";")+ 1, linea.length());
                
                strNombre = linea.substring(0, linea.indexOf(";"));
                linea = linea.substring(linea.indexOf(";")+ 1, linea.length());
                
                strApellidos = linea.substring(0, linea.indexOf(";"));              
                linea = linea.substring(linea.indexOf(";")+ 1, linea.length());
                
                strEdad = linea.substring(0, linea.indexOf(";"));
                linea = linea.substring(linea.indexOf(";")+ 1, linea.length());
                
                strProfesion = linea.substring(0, linea.indexOf(";"));
                linea = linea.substring(linea.indexOf(";")+ 1, linea.length());
                
                strGenero = linea.substring(0, linea.indexOf(";"));
                linea = linea.substring(linea.indexOf(";")+ 1, linea.length());
                
                strSiglas = linea.substring(0, linea.indexOf(";"));
                linea = linea.substring(linea.indexOf(";")+ 1, linea.length());
                
                strEncuesta[0] = linea.substring(0, linea.indexOf(";"));
                linea = linea.substring(linea.indexOf(";")+ 1, linea.length());
                
                strEncuesta[1] = linea.substring(0, linea.indexOf(";"));
                linea = linea.substring(linea.indexOf(";")+ 1, linea.length());
                
                strCuota = linea.substring(0, linea.indexOf(";"));
                linea = linea.substring(linea.indexOf(";")+ 1, linea.length());
                
                strCarne = linea.substring(0, linea.indexOf(";"));
                
                mili = new Militante();
             
                mili.setTipo(strSoM);
                mili.setNombre(strNombre);
                mili.setApellidos(strApellidos);
                mili.setEdad(Integer.valueOf(strEdad));
                mili.setProfesion(strProfesion);
                mili.setGenero(strGenero.charAt(0));
                mili.setSiglas(strSiglas); 
                mili.setEncuestas(strEncuesta);
                mili.setCuota(Double.valueOf(strCuota));
                mili.setCarnet(strCarne);                
                
                listMili.add(mili);
                listMiem.add(mili);
                
                datos = new Vector();
                datos.addElement(strSoM);
                datos.addElement(strNombre);
                datos.addElement(strApellidos);
                datos.addElement(Integer.valueOf(strEdad));
                datos.addElement(strProfesion);
                datos.addElement(strGenero.charAt(0));
                datos.addElement(strSiglas);
                datos.addElement(strEncuesta[0]);
                datos.addElement(strEncuesta[1]);
                datos.addElement(Double.valueOf(strCuota));
                datos.addElement(strCarne);

                tmodelMiem.addRow(datos);
                jTableMiem.setModel(tmodelMiem);
      
                //Escribirlo en consola
                System.out.print(" Tipo de votante:"+strSoM);
                System.out.print(" Nombre:"+strNombre);
                System.out.print(" Apellidos:"+strApellidos); 
                System.out.print(" Edad:"+Integer.valueOf(strEdad));
                System.out.print(" Profesión:"+strProfesion);
                System.out.print(" Género:"+strGenero.charAt(0));
                System.out.print(" Siglas:"+strSiglas);
                System.out.print(" Pregunta 1:"+strEncuesta[0]);
                System.out.print(" Pregunta 2:"+strEncuesta[1]);
                System.out.print(" Cuota:"+Double.valueOf(strCuota));
                System.out.println(" Carnet:"+strCarne);
            }                        
            //Contador de militantes
            System.out.println("Cantidad Militantes " + listMili.size());                       
        }
        catch(IOException e)
        {
            System.out.println("Error en la lectura del archivo");
        }
    }   
}
