/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoVentana;

import proyectoVentana.jfMiembros;
import proyecto.PartidoPolitico;
import java.io.BufferedInputStream;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZHONG HAO LIN CHEN, ADRIAN DAVID MORILLAS MARCO, CLARA EUGENIA PALOMARES CALVO
 */
public class jfPartidoPolitico extends javax.swing.JFrame {
    
    Vector datos = new Vector();
    ArrayList<PartidoPolitico> listPartPoli;  //Lista de partidos
    DefaultTableModel tmodelPartPoli = new DefaultTableModel();

    /**
     * Creates new form jfPartidoPolitico
     */
    public jfPartidoPolitico() {
        initComponents();
        
        //Centrar la ventana
        this.setLocationRelativeTo(null);
        
        listPartPoli = new ArrayList<PartidoPolitico>(); //Creamos una nueva lista de partidos
        
        tmodelPartPoli.addColumn("Nombre");
        tmodelPartPoli.addColumn("Siglas");
        tmodelPartPoli.addColumn("Logo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelPartido = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonElaList = new javax.swing.JButton();
        jLabelNombrePartido = new javax.swing.JLabel();
        jTextFieldNomPar = new javax.swing.JTextField();
        jLabelSiglas = new javax.swing.JLabel();
        jTextFieldSiglas = new javax.swing.JTextField();
        jLabelLogo = new javax.swing.JLabel();
        jTextFieldLogo = new javax.swing.JTextField();
        jScrollPaneMili = new javax.swing.JScrollPane();
        jTablePartPoli = new javax.swing.JTable();
        jButtonGuardarLista = new javax.swing.JButton();
        jButtonCargarLista = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomFichero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(150, 200, 240));

        jLabelPartido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPartido.setText("Partidos Politicos");

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonElaList.setText("Elaborar Lista del Partido seleccionado");
        jButtonElaList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonElaListActionPerformed(evt);
            }
        });

        jLabelNombrePartido.setText("Nombre");

        jTextFieldNomPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomParActionPerformed(evt);
            }
        });

        jLabelSiglas.setText("Siglas");

        jTextFieldSiglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSiglasActionPerformed(evt);
            }
        });

        jLabelLogo.setText("Logo");

        jTextFieldLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLogoActionPerformed(evt);
            }
        });

        jTablePartPoli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Siglas", "Logo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneMili.setViewportView(jTablePartPoli);

        jButtonGuardarLista.setText("Guardar lista de partidos");
        jButtonGuardarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarListaActionPerformed(evt);
            }
        });

        jButtonCargarLista.setText("Cargar lista de partidos");
        jButtonCargarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarListaActionPerformed(evt);
            }
        });

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre del fichero a guardar o cargar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonCargarLista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGuardarLista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNomFichero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelPartido)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAgregar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelSiglas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNombrePartido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldSiglas)
                                    .addComponent(jTextFieldNomPar)
                                    .addComponent(jTextFieldLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPaneMili, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonElaList)))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabelPartido)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombrePartido)
                    .addComponent(jTextFieldNomPar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSiglas)
                    .addComponent(jTextFieldSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogo)
                    .addComponent(jTextFieldLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAgregar)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonElaList, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneMili, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonGuardarLista)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCargarLista)
                            .addComponent(jTextFieldNomFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(117, 117, 117))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 514, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        PartidoPolitico partPoli = new PartidoPolitico(); //Creamos un nuevo partido politico de la Clase PartidoPolitico

        //Le asignamos el nombre, siglas y logo del texto que hemos rellenado en la interfaz
        partPoli.setNombre(jTextFieldNomPar.getText());
        partPoli.setSiglas(jTextFieldSiglas.getText());
        partPoli.setLogo(jTextFieldLogo.getText());

        listPartPoli.add(partPoli);

        //A la hora de rellenar la tabla tambien le añadiremos lo que hemos escrito en la barra de texto
        datos = new Vector();
        datos.addElement(jTextFieldNomPar.getText());
        datos.addElement(jTextFieldSiglas.getText());
        datos.addElement(jTextFieldLogo.getText());

        tmodelPartPoli.addRow(datos);

        jTablePartPoli.setModel(tmodelPartPoli);

        //Imprimir por consola partido añadido
        System.out.print(" Nombre:"+jTextFieldNomPar.getText());
        System.out.print(" Siglas:"+jTextFieldSiglas.getText());
        System.out.println(" Logo:"+jTextFieldLogo.getText());
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonCargarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarListaActionPerformed
        this.LeerArchivoLista(); //Invocamos el metodo de Leer para que el boton cargue nuestra lista de partidos
    }//GEN-LAST:event_jButtonCargarListaActionPerformed

    private void jButtonGuardarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarListaActionPerformed
        this.Guardar(); //Invocamos el metodo Guardar para que el boton guarde nuestra lista de partidos
    }//GEN-LAST:event_jButtonGuardarListaActionPerformed

    private void jTextFieldLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLogoActionPerformed
        //Barra para rellenar el logo del partido
    }//GEN-LAST:event_jTextFieldLogoActionPerformed

    private void jTextFieldSiglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSiglasActionPerformed
        //Barra para rellenar las siglas del partido
    }//GEN-LAST:event_jTextFieldSiglasActionPerformed

    private void jTextFieldNomParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomParActionPerformed
        //Barra para poner el nombre del partido
    }//GEN-LAST:event_jTextFieldNomParActionPerformed

    private void jButtonElaListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonElaListActionPerformed
        jfMiembros objMilitante = new jfMiembros(); //Cada vez que pulsamos el boton creamos una nueva lista de militantes a rellenar en una nueva ventana

        String valorSeleccionado = "";  //String incializado a vacio
        valorSeleccionado = this.jTablePartPoli.getValueAt(jTablePartPoli.getSelectedRow(),1).toString(); //Al String anterior le asignamos las siglas del partido que hemos seleccionado y creamos su lista

        objMilitante.setPartido(valorSeleccionado); //Asignamos el partido seleccionado para hacer la lista
        //objMilitante.setPartido(this.txtSeleccionado.getText());
        objMilitante.setVisible(true);//Hacemos visible la ventana de lista de militantes
    }//GEN-LAST:event_jButtonElaListActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalirActionPerformed
   

    
    private void Guardar(){
        try {
            String nomArch = jTextFieldNomFichero.getText();           
            //Aqui asignamos donde queremos guardar el fichero txt
            BufferedWriter out = new BufferedWriter(new FileWriter(nomArch));
            //Este bucle for recorre toda la lista de partidos politicos y va escribiendo en orden nombre, siglas y logo
            
            for(PartidoPolitico pp:this.listPartPoli){
                
                //Nombre
                out.write(pp.getNombre() + ";");
                 
                 //Siglas
                out.write(pp.getSiglas() + ";");
                
                //Logo
                out.write(pp.getLogo() + ";");
                
                //Salto de linea
                out.write(System.getProperty("line.separator"));
            }          
            out.close();
        } catch (IOException e) {}
    }  
    
    private void LeerArchivoLista(){
        try 
        {
            String nomArch = jTextFieldNomFichero.getText();
            FileInputStream fis = new FileInputStream(nomArch); 
            BufferedInputStream bis = new BufferedInputStream(fis); 
            DataInputStream dis = null; 
            
            //Inicializamos las cadenas en vacio
            dis = new DataInputStream(bis); 
            String linea = "";
            String strNombre = "";
            String strSiglas = "";
            String strLogo = "";
            PartidoPolitico partPoli;
            
            //Bucle para recorrer por linea del txt de la lista de partidos politicos
            while ((linea = dis.readLine()) != null ) 
            {                 
                strNombre = linea.substring(0, linea.indexOf(";"));
                linea = linea.substring(linea.indexOf(";")+ 1, linea.length());
                
                strSiglas = linea.substring(0, linea.indexOf(";"));
                
                linea = linea.substring(linea.indexOf(";")+ 1, linea.length());
                strLogo = linea.substring(0, linea.indexOf(";"));
                
                //Llenando la lista de los partidos politicos
                partPoli = new PartidoPolitico();
             
                partPoli.setNombre(strNombre);
                partPoli.setSiglas(strSiglas);
                partPoli.setLogo(strLogo);
             
                listPartPoli.add(partPoli);
                
                //Llenado de la tabla
                datos = new Vector();
                datos.addElement(strNombre);
                datos.addElement(strSiglas);
                datos.addElement(strLogo);

                tmodelPartPoli.addRow(datos);
                jTablePartPoli.setModel(tmodelPartPoli);
                
                //Escribirlo en consola
                System.out.print(" Nombre:"+strNombre);
                System.out.print(" Siglas:"+strSiglas);
                System.out.println(" Logo:"+strLogo);                 
           }            
            //Contador de partidos
            System.out.println("Cantidad Partidos Politicos " + listPartPoli.size());
               
        }
        catch(IOException e)
        {
            System.out.println("Error en la lectura del archivo");//Mensaje de error de lectura
        }
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPartidoPolitico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPartidoPolitico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPartidoPolitico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPartidoPolitico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPartidoPolitico().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCargarLista;
    private javax.swing.JButton jButtonElaList;
    private javax.swing.JButton jButtonGuardarLista;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombrePartido;
    private javax.swing.JLabel jLabelPartido;
    private javax.swing.JLabel jLabelSiglas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneMili;
    private javax.swing.JTable jTablePartPoli;
    private javax.swing.JTextField jTextFieldLogo;
    private javax.swing.JTextField jTextFieldNomFichero;
    private javax.swing.JTextField jTextFieldNomPar;
    private javax.swing.JTextField jTextFieldSiglas;
    // End of variables declaration//GEN-END:variables
}
